# Generated by Django 5.0.1 on 2024-02-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=50)),
                ('adminPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stu_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_FistName', models.CharField(max_length=100)),
                ('stu_LastName', models.CharField(max_length=100)),
                ('stu_RollNo', models.CharField(max_length=100)),
                ('stu_Email', models.EmailField(max_length=100)),
                ('stu_Contact', models.IntegerField(max_length=100)),
                ('stu_Fee', models.IntegerField(max_length=100)),
                ('stu_Course', models.CharField(max_length=100)),
                ('stu_Branch', models.CharField(max_length=100)),
                ('stu_Year', models.IntegerField(max_length=100)),
            ],
        ),
    ]
