# Generated by Django 5.0.1 on 2024-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='stu_Contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='stu_Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='stu_Fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stu_details',
            name='stu_Year',
            field=models.IntegerField(),
        ),
    ]
