# Generated by Django 5.0.1 on 2024-02-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stu_formdetails_teach_formdetails_delete_stu_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
