# Generated by Django 5.0.1 on 2024-02-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_stu_details_stu_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_Branch',
        ),
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_Contact',
        ),
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_Course',
        ),
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_Email',
        ),
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_Fee',
        ),
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_LastName',
        ),
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_RollNo',
        ),
        migrations.RemoveField(
            model_name='stu_details',
            name='stu_Year',
        ),
    ]
