# Generated by Django 5.0.1 on 2024-02-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stu_formdetails_stu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_image',
            field=models.ImageField(upload_to='uploads/images/'),
        ),
    ]
