# Generated by Django 5.0.1 on 2024-02-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_stu_formdetails_delete_stu_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_ID', models.CharField(max_length=100)),
                ('stu_Name', models.CharField(max_length=100)),
                ('stu_FatherName', models.CharField(max_length=100)),
                ('stu_DOB', models.DateField(auto_now=True)),
                ('stu_Email', models.EmailField(max_length=100)),
                ('stu_Mobile', models.IntegerField()),
                ('stu_Address', models.CharField(max_length=100)),
                ('stu_Gender', models.CharField(max_length=10)),
                ('stu_Cast', models.CharField(max_length=10)),
                ('stu_Qualification', models.CharField(max_length=50)),
                ('stu_Department', models.CharField(max_length=50)),
                ('stu_Course', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Stu_FormDetails',
        ),
    ]
