# Generated by Django 5.0.1 on 2024-02-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_stu_details_delete_stu_formdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_details',
            name='stu_Mobile',
            field=models.IntegerField(max_length=99999999999),
        ),
    ]
