# Generated by Django 5.0.1 on 2024-02-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_stu_details_stu_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_ID', models.CharField(max_length=100)),
                ('stu_Name', models.CharField(max_length=100)),
                ('stu_DOB', models.DateField(auto_now=True)),
                ('stu_Email', models.EmailField(max_length=100)),
                ('stu_Mobile', models.IntegerField(max_length=99999999999)),
                ('stu_Gender', models.CharField(max_length=10)),
                ('stu_Department', models.CharField(max_length=50)),
                ('stu_Course', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teach_FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_ID', models.CharField(max_length=100)),
                ('teach_jtitle', models.CharField(max_length=100)),
                ('teach_Name', models.CharField(max_length=100)),
                ('teach_DOB', models.DateField(auto_now=True)),
                ('teach_Email', models.EmailField(max_length=100)),
                ('teach_Mobile', models.IntegerField(max_length=99999999999)),
                ('teach_Gender', models.CharField(max_length=10)),
                ('teach_Course', models.CharField(max_length=50)),
            ],
        ),
    ]
