# Generated by Django 5.0.1 on 2024-02-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_stu_formdetails_delete_stu_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach_FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach_ID', models.CharField(max_length=100)),
                ('teach_jtitle', models.CharField(max_length=100)),
                ('teach_Name', models.CharField(max_length=100)),
                ('teach_DOB', models.DateField(auto_now=True)),
                ('teach_Email', models.EmailField(max_length=100)),
                ('teach_Mobile', models.IntegerField(max_length=99999999999)),
                ('teach_Gender', models.CharField(max_length=10)),
                ('teach_Course', models.CharField(max_length=50)),
            ],
        ),
    ]
