# Generated by Django 5.0.1 on 2024-02-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_stu_formdetails_teach_formdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stu_Details',
        ),
    ]
