# Generated by Django 5.0.1 on 2024-02-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20240205_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_Mobile',
            field=models.IntegerField(),
        ),
    ]
