# Generated by Django 4.2.5 on 2024-02-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_stu_details_teach_details_delete_stu_formdetails_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stu_Details',
            new_name='Stu_FormDetails',
        ),
        migrations.RenameModel(
            old_name='Teach_Details',
            new_name='Teach_FormDetails',
        ),
    ]
