# Generated by Django 5.0.1 on 2024-02-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_stu_details_stu_formdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_formdetails',
            name='stu_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
