# Generated by Django 5.0.1 on 2024-02-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_stu_formdetails_stu_mobile_and_more'),
        ('app', '0015_alter_stu_formdetails_stu_emmobile_and_more'),
    ]

    operations = [
    ]
