# Generated by Django 5.0.1 on 2024-02-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_stu_formdetails_stu_emmobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_formdetails',
            name='stu_Course_Fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_Adhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_DOBjob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_Graduation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_Add',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_Adhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_DOBjob',
            field=models.DateField(null=True),
        ),
    ]
