# Generated by Django 5.0.1 on 2024-02-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_stu_formdetails_stu_course_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_Branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stu_formdetails',
            name='stu_Collage',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_Department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_EmMobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_Graduation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_Mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teach_formdetails',
            name='teach_Postgraduation',
            field=models.CharField(max_length=50),
        ),
    ]
